### ISSUE TITLE
I am an idiot, sure. Help me anyway pls!

### ISSUE THREAD

**Issue by Adrianzo** [OliverUv/quickswitch-for-i3#10]
Installed on Ubuntu 15.10 with:
$ pip install quickswitch-i3
and added this line (before issuing i3 restart) to my config:
bindsym $mod+q exec --no-startup-id quickswitch-i3

But nothing happens when I press $mod+q...

EDIT: solved by manually installing, replaced config line with bindsym $mod+q exec --no-startup-id ~/bin/i3quickswitch.py

**Comment by OliverUv** [comment]
Ah, the pip stuff is something I inherited from previous maintainers/authors. `pip install quickswitch-i3` will not install this version, but the old unmaintained one.

The solution you came up with is what I use, too. Sad to say I've no time to hack on quickswitch at the moment, or in the forseeable future :(((((. Closing this issue but opening one for getting pip stuff figured out.
