### ISSUE TITLE
quickswitch-i3 can't be launched on Ubuntu 16.04

### ISSUE THREAD

**Issue by ufengger** [OliverUv/quickswitch-for-i3#17]
Hi,

I installed the quickswitch from your github, but I can't launch it. The error message is:

> Traceback (most recent call last):
  File "quickswitch.py", line 544, in <module>
    main()
  File "quickswitch.py", line 491, in main
    if args.dmenu == default_dmenu_command and not check_dmenu():
  File "quickswitch.py", line 48, in check_dmenu
    return bool(shutil.which("dmenu"))
AttributeError: 'module' object has no attribute 'which'

My os is Ubuntu 16.04 with i3 version 4.13. Do you know how to fix it?

**Comment by enkore** [comment]
You probably need to run it with Python 3.

**Comment by ufengger** [comment]
OK, thanks so much!
