### ISSUE TITLE
Add keybinds to launch modes when quickswitch is already open

### ISSUE THREAD

**Issue by indeedwatson** [OliverUv/quickswitch-for-i3#20]
Instead of having to launch quickswitch with, for example, the `-m` flag, I'd like to launch it normally and press, say `shift + enter` if instead of the normal focus switch I want to move the window to the current workspace.

**Comment by OliverUv** [comment]
Are you thinking of `dmenu` ? quickswitch is not a program that runs in the background, you start it, it runs and finishes what it's doing, and then it closes.

I would suggest adding a keybind to your i3 config, which runs quickswitch with the `-m` flag (if that's the effect you want).

You can see how I'm using it here: https://github.com/OliverUv/Configuration-files/blob/ae2fce77efa76581f570c564203ad8531e45a30c/i3config.base#L182

Note that `$quickbin` is just a shorthand for `python3 ~/Projects/quickswitch-for-i3/quickswitch.py` (defined on line 19 in the same file)

**Comment by indeedwatson** [comment]
I understand what you mean but that's not how my workflow goes. I don't want to think whether I want to bring the window to current ws or just focus it before i open the program, nor do I want to have 2 separate keybinds for those two things, I want to find the window I want and then decide what I want to do with it via different keybinds.

I found a way to emulate this behavior in rofi, if I press enter it focuses, if I press shift+enter it brings the window to current ws.

**Comment by OliverUv** [comment]
Ah, yes. Sadly this isn't something easily doable with quickswitch and dmenu. It would need some major changes to dmenu, which I wouldn't bet on the people running that project would be interested in.

All quickswitch does is do whatever you ask it to do. It can give you a list of windows. It can do something with a window, or workspace, or something. But it never has state, never has any UI by itself.

dmenu is just a sort-of convenient ui to use to select things from lists, which may come from quickswitch, and maybe the selected item is given to quickswitch as an argument when it's run.

Happy to hear rofi is working out for you. I'll probably end up switching to it too, at some point.
