### ISSUE TITLE
launch application if no window found

### ISSUE THREAD

**Issue by k0377** [OliverUv/quickswitch-for-i3#8]
As it seems, this https://github.com/i3/i3/issues/1783 doesnt really work, can you add an option, to launch the application if no entry is found? Say, I wanna focus libreoffice-writer, so I type `writer` but there is no such window then pull in `i3-dmenu-desktop` and open the application.

**Comment by OliverUv** [comment]
Should be doable! Think I'll whip something up on Sunday. Will notify you here, as I'd appreciate it if you want to use it for a week or two before I put it in `master`.

**Comment by k0377** [comment]
Wow cool, thanks for the response! Would be great and of course i gonna test this! But what's that white thingy? http://vvv.uvman.se/ :thought_balloon: :smile_cat:

**Comment by OliverUv** [comment]
Hi! I forgot all about this over the weekend. I'll get to it after I finish some other tasks. PS: The orb is an illustrious being, who has the power to drain laptop batteries and make GPU fans spin at 100%, quite unnecessarily!

**Comment by k0377** [comment]
kiss ya cheek :kissing_cat:

**Comment by OliverUv** [comment]
Hi there, sorry for the delay! Can you check this branch out and use it a bit?

https://github.com/OliverUv/quickswitch-for-i3/tree/launch

Report back to me if there are any problems, otherwise I will merge this into master soon-ish.

**Comment by k0377** [comment]
yay it works, thank ya! :heart:
